build: fix ant test which does not work with ant version 1.9
ant 1.9 + external junit4.jar does not work:
   ...snip...
   test:
       [junit] Running com.github.perlundq.yajsync.session.IntegerCoderTest
       [junit] Testsuite: com.github.perlundq.yajsync.session.IntegerCoderTest
       [junit] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 sec
       [junit] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 sec
       [junit]
       [junit]     Caused an ERROR
       [junit] junit/framework/JUnit4TestAdapterCache
       [junit] java.lang.NoClassDefFoundError: junit/framework/JUnit4TestAdapterCache
   ...snip...

Fixed by enabling fork for the ant junit task. Tested with ant 1.8 and
ant 1.9.

See also:
http://ant.apache.org/manual/Tasks/junit.html
https://github.com/real-logic/simple-binary-encoding/issues/96